select '00:00-08:00' as [Time]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=00 and datepart(hh,dateoccured)<8 and weekday_nm='Monday' and RequestTypeNew=1) as [Monday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=00 and datepart(hh,dateoccured)<8 and weekday_nm='Tuesday' and RequestTypeNew=1) as [Tuesday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=00 and datepart(hh,dateoccured)<8 and weekday_nm='Wednesday' and RequestTypeNew=1) as [Wednesday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=00 and datepart(hh,dateoccured)<8 and weekday_nm='Thursday' and RequestTypeNew=1) as [Thursday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=00 and datepart(hh,dateoccured)<8 and weekday_nm='Friday' and RequestTypeNew=1) as [Friday]
UNION ALL
select '08:00-09:00' as [Time]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=8 and datepart(hh,dateoccured)<9 and weekday_nm='Monday' and RequestTypeNew=1) as [Monday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=8 and datepart(hh,dateoccured)<9 and weekday_nm='Tuesday' and RequestTypeNew=1) as [Tuesday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=8 and datepart(hh,dateoccured)<9 and weekday_nm='Wednesday' and RequestTypeNew=1) as [Wednesday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=8 and datepart(hh,dateoccured)<9 and weekday_nm='Thursday' and RequestTypeNew=1) as [Thursday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=8 and datepart(hh,dateoccured)<9 and weekday_nm='Friday' and RequestTypeNew=1) as [Friday]
UNION ALL
select '09:00-10:00' as [Time]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=9 and datepart(hh,dateoccured)<10 and weekday_nm='Monday' and RequestTypeNew=1) as [Monday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=9 and datepart(hh,dateoccured)<10 and weekday_nm='Tuesday' and RequestTypeNew=1) as [Tuesday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=9 and datepart(hh,dateoccured)<10 and weekday_nm='Wednesday' and RequestTypeNew=1) as [Wednesday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=9 and datepart(hh,dateoccured)<10 and weekday_nm='Thursday' and RequestTypeNew=1) as [Thursday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=9 and datepart(hh,dateoccured)<10 and weekday_nm='Friday' and RequestTypeNew=1) as [Friday]
UNION ALL
select '10:00-11:00' as [Time]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=10 and datepart(hh,dateoccured)<11 and weekday_nm='Monday' and RequestTypeNew=1) as [Monday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=10 and datepart(hh,dateoccured)<11 and weekday_nm='Tuesday' and RequestTypeNew=1) as [Tuesday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=10 and datepart(hh,dateoccured)<11 and weekday_nm='Wednesday' and RequestTypeNew=1) as [Wednesday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=10 and datepart(hh,dateoccured)<11 and weekday_nm='Thursday' and RequestTypeNew=1) as [Thursday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=10 and datepart(hh,dateoccured)<11 and weekday_nm='Friday' and RequestTypeNew=1) as [Friday]
UNION ALL
select '11:00-12:00' as [Time]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=11 and datepart(hh,dateoccured)<12 and weekday_nm='Monday' and RequestTypeNew=1) as [Monday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=11 and datepart(hh,dateoccured)<12 and weekday_nm='Tuesday' and RequestTypeNew=1) as [Tuesday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=11 and datepart(hh,dateoccured)<12 and weekday_nm='Wednesday' and RequestTypeNew=1) as [Wednesday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=11 and datepart(hh,dateoccured)<12 and weekday_nm='Thursday' and RequestTypeNew=1) as [Thursday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=11 and datepart(hh,dateoccured)<12 and weekday_nm='Friday' and RequestTypeNew=1) as [Friday]
UNION ALL
select '12:00-13:00' as [Time]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=12 and datepart(hh,dateoccured)<13 and weekday_nm='Monday' and RequestTypeNew=1) as [Monday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=12 and datepart(hh,dateoccured)<13 and weekday_nm='Tuesday' and RequestTypeNew=1) as [Tuesday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=12 and datepart(hh,dateoccured)<13 and weekday_nm='Wednesday' and RequestTypeNew=1) as [Wednesday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=12 and datepart(hh,dateoccured)<13 and weekday_nm='Thursday' and RequestTypeNew=1) as [Thursday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=12 and datepart(hh,dateoccured)<13 and weekday_nm='Friday' and RequestTypeNew=1) as [Friday]
UNION ALL
select '13:00-14:00' as [Time]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=13 and datepart(hh,dateoccured)<14 and weekday_nm='Monday' and RequestTypeNew=1) as [Monday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=13 and datepart(hh,dateoccured)<14 and weekday_nm='Tuesday' and RequestTypeNew=1) as [Tuesday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=13 and datepart(hh,dateoccured)<14 and weekday_nm='Wednesday' and RequestTypeNew=1) as [Wednesday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=13 and datepart(hh,dateoccured)<14 and weekday_nm='Thursday' and RequestTypeNew=1) as [Thursday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=13 and datepart(hh,dateoccured)<14 and weekday_nm='Friday' and RequestTypeNew=1) as [Friday]
UNION ALL
select '14:00-15:00' as [Time]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=14 and datepart(hh,dateoccured)<15 and weekday_nm='Monday' and RequestTypeNew=1) as [Monday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=14 and datepart(hh,dateoccured)<15 and weekday_nm='Tuesday' and RequestTypeNew=1) as [Tuesday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=14 and datepart(hh,dateoccured)<15 and weekday_nm='Wednesday' and RequestTypeNew=1) as [Wednesday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=14 and datepart(hh,dateoccured)<15 and weekday_nm='Thursday' and RequestTypeNew=1) as [Thursday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=14 and datepart(hh,dateoccured)<15 and weekday_nm='Friday' and RequestTypeNew=1) as [Friday]
UNION ALL
select '15:00-16:00' as [Time]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=15 and datepart(hh,dateoccured)<16 and weekday_nm='Monday' and RequestTypeNew=1) as [Monday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=15 and datepart(hh,dateoccured)<16 and weekday_nm='Tuesday' and RequestTypeNew=1) as [Tuesday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=15 and datepart(hh,dateoccured)<16 and weekday_nm='Wednesday' and RequestTypeNew=1) as [Wednesday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=15 and datepart(hh,dateoccured)<16 and weekday_nm='Thursday' and RequestTypeNew=1) as [Thursday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=15 and datepart(hh,dateoccured)<16 and weekday_nm='Friday' and RequestTypeNew=1) as [Friday]
UNION ALL
select '16:00-17:00' as [Time]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=16 and datepart(hh,dateoccured)<17 and weekday_nm='Monday' and RequestTypeNew=1) as [Monday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=16 and datepart(hh,dateoccured)<17 and weekday_nm='Tuesday' and RequestTypeNew=1) as [Tuesday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=16 and datepart(hh,dateoccured)<17 and weekday_nm='Wednesday' and RequestTypeNew=1) as [Wednesday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=16 and datepart(hh,dateoccured)<17 and weekday_nm='Thursday' and RequestTypeNew=1) as [Thursday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=16 and datepart(hh,dateoccured)<17 and weekday_nm='Friday' and RequestTypeNew=1) as [Friday]
UNION ALL
select '17:00-18:00' as [Time]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=17 and datepart(hh,dateoccured)<18 and weekday_nm='Monday' and RequestTypeNew=1) as [Monday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=17 and datepart(hh,dateoccured)<18 and weekday_nm='Tuesday' and RequestTypeNew=1) as [Tuesday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=17 and datepart(hh,dateoccured)<18 and weekday_nm='Wednesday' and RequestTypeNew=1) as [Wednesday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=17 and datepart(hh,dateoccured)<18 and weekday_nm='Thursday' and RequestTypeNew=1) as [Thursday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=17 and datepart(hh,dateoccured)<18 and weekday_nm='Friday' and RequestTypeNew=1) as [Friday]
UNION ALL
select '18:00-19:00' as [Time]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=18 and datepart(hh,dateoccured)<19 and weekday_nm='Monday' and RequestTypeNew=1) as [Monday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=18 and datepart(hh,dateoccured)<19 and weekday_nm='Tuesday' and RequestTypeNew=1) as [Tuesday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=18 and datepart(hh,dateoccured)<19 and weekday_nm='Wednesday' and RequestTypeNew=1) as [Wednesday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=18 and datepart(hh,dateoccured)<19 and weekday_nm='Thursday' and RequestTypeNew=1) as [Thursday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=18 and datepart(hh,dateoccured)<19 and weekday_nm='Friday' and RequestTypeNew=1) as [Friday]
UNION ALL
select '19:00-00:00' as [Time]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=19 and datepart(hh,dateoccured)<00 and weekday_nm='Monday' and RequestTypeNew=1) as [Monday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=19 and datepart(hh,dateoccured)<00 and weekday_nm='Tuesday' and RequestTypeNew=1) as [Tuesday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=19 and datepart(hh,dateoccured)<00 and weekday_nm='Wednesday' and RequestTypeNew=1) as [Wednesday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=19 and datepart(hh,dateoccured)<00 and weekday_nm='Thursday' and RequestTypeNew=1) as [Thursday]
, (select count(*) from faults join calendar on floor(cast(dateoccured as float))=floor(cast(start_dts as float)) where dateoccured>@startdate and dateoccured<@enddate and datepart(hh,dateoccured)>=19 and datepart(hh,dateoccured)<00 and weekday_nm='Friday' and RequestTypeNew=1) as [Friday]







